"""empty message

Revision ID: 956cf226eb71
Revises: fe39c6f751b5
Create Date: 2025-05-10 13:29:29.109788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956cf226eb71'
down_revision = 'fe39c6f751b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
