"""empty message

Revision ID: b757e75ac358
Revises: 9041571faa5a
Create Date: 2025-05-10 12:30:16.618664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b757e75ac358'
down_revision = '9041571faa5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tickets')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_tickets_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tickets_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('user_tickets',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('ticket_id', sa.INTEGER(), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name='fk_user_tickets_ticket_id_tickets'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_tickets_user_id_users')
    )
    # ### end Alembic commands ###
